Cbc 2.10
cyclus/cyclus pull request #1557
Opened 2021-03-15 20:20 UTC by bam241

This should enable compatibility with `cbc 2.10` 

I tested that on a docker ubuntu 20.04 it compiles and unit_tests are running fine.

maybe @nuclearkatie could confirm if that's is working for her...

2021-03-15 20:40 UTC, nuclearkatie commented
I was able to successfully install and run unit tests on a Ubuntu 20.04 VM using this. Thanks @bam241

2021-03-17 10:22 UTC, gonuke requested changes
Thanks for this quick fix @bam241  - just one comment

2021-03-17 10:22 UTC, gonuke commented on src/OsiCbcSolverInterface.cpp
> +#elif CBC_VERSION_MAJOR == 2 && CBC_VERSION_MINOR == 10
I know this pattern was inherited from before, but why not just include the `hpp` file here, instead?

2021-03-17 10:24 UTC, gonuke commented
Do we want to update CI to test with 2.10? Or both?

2021-03-22 18:35 UTC, bam241 commented
this is linked to #1262

2021-03-24 12:28 UTC, gonuke commented on src/OsiCbcSolverInterface.cpp
>  #include "OsiCbcSolverInterface_2_8.cpp"
I think we decided to include the `hpp` file here instead of duplicating this block

2021-03-24 12:30 UTC, gonuke commented on src/OsiCbcSolverInterface.hpp
> +#include "OsiCbcSolverInterface_2_10.hpp"
I think we decided:
```suggestion
#elif CBC_VERSION_MAJOR == 2 && CBC_VERSION_MINOR <= 10
#include "OsiCbcSolverInterface_2_10.hpp"
```

2021-03-24 12:30 UTC, gonuke commented on src/OsiCbcSolverInterface.hpp
> +#include "OsiCbcSolverInterface_2_10.hpp"
We can probably also delete the v2.9 hpp file.

2021-03-24 12:33 UTC, gonuke commented
I think there is still a question about how we test this.  If we had access to the right versions, we could test at merge, but even that may be a lot of effort.  I don't think we want/need to test in CI for every PR.

2021-04-26 18:52 UTC, bam241 commented on src/OsiCbcSolverInterface.cpp
> +#include "OsiCbcSolverInterface_2_10.hpp"
this should be `.cpp`

2021-04-26 18:52 UTC, bam241 commented
2.9 and 2.10 should be merged together as they are identical.

2021-07-12 12:24 UTC, bam241 commented
@gonuke There is something I don't understand.

the cmake file adds automatically all the *.cc files and manually `OsiCbcSolverInterface.cpp`
with this news implementation we only include `OsiCbcSolverInterface.hpp` from `OsiCbcSolverInterface.cpp`.
 `OsiCbcSolverInterface.hpp` conditionally include the proper  `OsiCbcSolverInterface_x_Y.hpp` header.
but how are the symbol added to the library as we don't add the `OsiCbcSolverInterface_x_Y.cpp` to the built library.

(I believe the include that existed before served that purpose...)

2021-07-12 12:29 UTC, gonuke commented
I think you are right.  I probably misread the includes and assumed they were HPP files, but they are in fact CPP files.

2021-07-14 13:53 UTC, gonuke approved these changes

2021-07-14 13:55 UTC, gonuke requested changes
Be sure to include cpp files where they are needed

2021-07-14 13:55 UTC, gonuke commented on src/OsiCbcSolverInterface.cpp
> +// #endif
I think we need to revert this change, right? and make sure to include the `*.cpp` files here.

2021-07-20 13:32 UTC, gonuke approved these changes

2021-07-20 13:32 UTC, gonuke commented
this looks good - I'll wait for tests to finish

2021-07-20 13:58 UTC, gonuke commented
Why are all our material tests failing?

2021-07-20 14:10 UTC, bam241 commented
root cause might come from composition.

I need to investigate....

2021-07-20 15:02 UTC, gonuke commented
We definitely changed PyNE in this space - but have we updated PyNE in CI or in our build since those changes?
Should we be submoduling PyNE?

2021-07-20 17:06 UTC, bam241 commented
this is very strange, I can't reproduce that in docker using the same image we run on CI...

2021-07-20 17:09 UTC, bam241 commented
can this be a ressource issue ?

2021-07-22 21:52 UTC, bam241 commented
this needs #1567 to pass

2021-07-22 22:44 UTC, gonuke commented
rebase this for tests to work!?!?

2021-07-26 18:08 UTC, gonuke commented
Thanks @bam241

2021-07-26 18:08 UTC, merged