Circle 2 GitHubAction
cyclus/cyclus pull request #1569
Opened 2021-07-30 15:55 UTC by bam241

attempt to convert our Circle CI to GithubAction

2021-08-12 01:58 UTC, gonuke commented
This appears to be working, but I'll wait for you to convert it from draft

2021-08-13 05:55 UTC, bam241 commented
@gonuke I think I am happy with this now.

since your last review, I just removed from circleCI the items I transferred to GitHubAction (build, unit_test, nosetest) and added a news file...

2021-08-13 09:57 UTC, gonuke requested changes
This will need a rebase & change to CHANGELOG since I merged the CHANGELOG PR

2021-08-14 05:13 UTC, bam241 commented
@gonuke I rebased it.

2021-08-14 11:30 UTC, gonuke approved these changes
I'm approving because it has apparently been there a while, but with a question about `core-version`

2021-08-14 11:30 UTC, gonuke commented on .github/workflows/build_test.yml
> +                            --build-type=Release --core-version 999999.999999 \
Maybe I haven't noticed this before, but what is `core-version` and is this the right one?

2021-08-14 11:30 UTC, gonuke commented
Thanks @bam241

2021-08-14 11:30 UTC, merged