Updated Readme file to work properly with Ubuntu 22.04
cyclus/cyclus pull request #1617
Opened 2023-11-21 13:00 UTC by yvrob

Installation with Ubuntu 22.04 did not work because some conda packages were not compatible anymore.
Followed instructions on the docker installation, and tested it on a clean Ubuntu 22.04 system.

2023-11-21 16:15 UTC, gonuke requested changes
Thanks @yvrob for this contribution!  I wonder if you've tried with newer python versions?  I know 3.6 is too old, but we test with 3.11 in conda successfully.

2023-11-21 16:15 UTC, gonuke commented on README.rst
> +- ``conda create -n cyclus python=3.8``
Can you try this with python 3.11?  That is what works for our automated testing.

2023-11-21 16:54 UTC, yvrob commented
Dear Paul,

Thank, you I will try it and let you know.

Best,
Yves Robert




On Tue, Nov 21, 2023 at 11:16 AM Paul Wilson ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Thanks @yvrob <https://github.com/yvrob> for this contribution! I wonder
> if you've tried with newer python versions? I know 3.6 is too old, but we
> test with 3.11 in conda successfully.
> ------------------------------
>
> In README.rst
> <https://github.com/cyclus/cyclus/pull/1617#discussion_r1400840991>:
>
> > @@ -108,10 +108,13 @@ To install Cyclus and its dependencies onto a clean Ubuntu machine (tested on 18
>
>  - ``conda config --add channels conda-forge``
>
> -- ``conda install -y openssh gxx_linux-64 gcc_linux-64 cmake make docker-pycreds git xo
> -  python-json-logger python=3.6 glibmm glib=2.56 libxml2 libxmlpp libblas libcblas
> -  liblapack pkg-config coincbc=2.9 boost-cpp hdf5 sqlite pcre gettext bzip2 xz
> -  setuptools nose pytables pandas jinja2 cython==0.26 websockets pprintpp``
> +- ``conda create -n cyclus python=3.8``
>
> Can you try this with python 3.11? That is what works for our automated
> testing.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/cyclus/cyclus/pull/1617#pullrequestreview-1742415431>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANNXOHCVCUYK3E73ZBJ45PTYFTHUBAVCNFSM6AAAAAA7URBBJCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTONBSGQYTKNBTGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-11-28 13:08 UTC, yvrob commented
Dear Paul,

Thank you very much, it should be updated now.

Best regards,
Yves

2023-11-28 14:06 UTC, gonuke commented
Thanks for providing this update @yvrob - I'll merge them in shortly.  Hopefully, we can issue a new release soon and include even more extensive updates to aid new users installation.

2023-11-28 14:07 UTC, gonuke requested changes
It look like we need one other change, after all.  We require all PRs to include an update to the `CHANGELOG.rst` file, with mention of the PR number.  Please make a new addition to this file and add that file to this PR.

2023-11-28 15:06 UTC, yvrob commented
Dear Paul,

Thank you for pointing this out. I made the update. Please let me know if
everything looks good now.

Best regards,

Yves



On Tue, Nov 28, 2023 at 9:08 AM Paul Wilson ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> It look like we need one other change, after all. We require all PRs to
> include an update to the CHANGELOG.rst file, with mention of the PR
> number. Please make a new addition to this file and add that file to this
> PR.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/cyclus/cyclus/pull/1617#pullrequestreview-1752987753>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANNXOHE34BI4FGW4SY27DG3YGXV4BAVCNFSM6AAAAAA7URBBJCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTONJSHE4DONZVGM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-11-28 18:34 UTC, merged