warning and limit for splitting resources into too many packages
cyclus/cyclus pull request #1771
Opened 2024-07-10 00:33 UTC by nuclearkatie

Adds a warning value (one milion) and a limit value (unsigned int / 10) for re-packaging. Implemented in Material Sell Policy, when calculating how many bids to respond with, and in the repackaging process itself (in Resource). If trying (or in the case of sell pol, intending) to repackage a single resource into more than warn/limit values, raise warning/limit

Closes #1766

2024-07-10 02:01 UTC, nuclearkatie commented
aha, this has raised an additional issue that trying to convert a float to int (for the number of bids to respond with) can have overflow issues even before we deal with the limits on vector length.

I think this gives us an additional point at which we need to throw an error, I don't think we should be proceeding at all if overflow errors are raised

2024-07-11 00:06 UTC, gonuke requested changes
This looks good to me, but it seems like the conditions could become more complicated so I wonder if we make it a function?

2024-07-11 00:06 UTC, gonuke commented on src/resource.h
> +  if (approx_num_pkgs > Package::SplitLimit() || approx_num_pkgs == std::numeric_limits<int>::min()) {
I wonder about making a function `Package::ExceedsSplitLimit(approx_num_pkgs)` that can handle these two variations of ways to exceed the limit - and any other we find?

2024-07-13 22:12 UTC, gonuke approved these changes
This looks good to me - thanks @nuclearkatie

2024-07-13 22:12 UTC, merged