Update stubs for newer build infrastructure
cyclus/cyclus pull request #1789
Opened 2024-08-28 12:04 UTC by gonuke

Minor changes to CMake config and install script to match newest cyclus build.

Fixes #1788 

Should probably devise a test for this?

2024-08-28 20:19 UTC, bennibbelink requested changes
What kind of test? Sorry I'm not sure I follow

2024-08-28 20:19 UTC, bennibbelink commented on stubs/CMakeLists.txt
> +CHECK_CXX_COMPILER_FLAG("-std=c++17" COMPILER_SUPPORTS_CXX11)
```suggestion
CHECK_CXX_COMPILER_FLAG("-std=c++17" COMPILER_SUPPORTS_CXX17)
```

2024-08-28 20:19 UTC, bennibbelink commented on stubs/CMakeLists.txt
>  IF(COMPILER_SUPPORTS_CXX11)
```suggestion
IF(COMPILER_SUPPORTS_CXX17)
```

2024-08-29 01:11 UTC, gonuke commented
> What kind of test? Sorry I'm not sure I follow

I'll confess that I'm not sure what the test would be either.  It would start by running cycstub to generate a stub archetype and then some combination of:
* confirming that it's `CMakeLists.txt` file is compatible with the main cyclus one (somehow???(
* building the stub and ensuring it loads with cyclus

2024-08-31 22:18 UTC, bennibbelink commented
There is a lot of redundancy between `stubs/CMakeLists.txt` and root `CMakeLists.txt`.  What if we write a module in `cmake/` to hold most of the boilerplate and call it `SetupCyclusBuild.cmake` or `CyclusBuildPreamble.cmake` (or something along those lines) so that the same CMake code can be used in the `CmakeLists.txt` and `stubs/CmakeLists.txt`.  The modules in `cmake/` are installed as part of the build already, so we should be able to do the same thing in cycamore too and reduce redundancy across repos.  I can try to implement this over the long weekend.

As for the tests, it looks like `tests/test_stubs.py` does what you're describing (?).  Do we need to expand on this?

2024-09-01 01:02 UTC, bennibbelink commented
> What if we write a module in `cmake/`

https://github.com/bennibbelink/cyclus/tree/cmake-boilerplate this is sort of a minimum viable product of what I mean.  We could choose to wrap more of it in macros if we want (e.g. finding and linking against packages) but I think there is probably a balance to find - verbosity is helpful to convey what is actually being done but abstracting the code out to macros should reduce redundancy across builds and help maintainability.  Curious to hear your thoughts @gonuke.

2024-09-02 00:26 UTC, gonuke commented
Is this partly what the `UseCyclus` macro is meant to do? I definitely like this idea!

2024-09-02 12:13 UTC, bennibbelink commented
Yes, but the macros in `UseCyclus.cmake` are targeted towards building agent libraries.  We can add build setup macros to that file or a different one, doesn't really matter.  I'd probably lean towards having another file to separate concerns but if you think we should keep them all in one place thats no problem

2024-09-02 12:27 UTC, gonuke commented
Another file is fine - thanks

2024-09-02 15:26 UTC, bennibbelink commented
Closing this PR in favor of #1793.

2024-09-02 15:26 UTC, closed without merging