Modify Cython api to use `api` keyword
cyclus/cyclus pull request #1809
Opened 2024-09-21 13:38 UTC by bennibbelink

I stumbled upon [this section ](https://cython.readthedocs.io/en/latest/src/userguide/external_C_code.html#c-api-declarations)of the cython docs (I can't believe I missed it before!!) that discusses how to make cython declarations available to C code.  Since we only access cython methods in PyHooks we can define those methods with the `api` keyword and avoid dealing with the messy multi-phase module initialization (see #1781).  It also does not require that `libcyclus` is linked with our cython modules since "the Python import machinery is used to make the connection dynamically" (if you look at the generated `_api.h` headers it looks like they are doing a lot of the messy Python C-API calls that I was making in #1781, but in a robust/correct way :smile:).

This PR replaces #1781 and closes #1779.

2024-09-22 20:07 UTC, gonuke requested changes
Thanks @bennibbelink - I'm not sure I understand all of this, but probably didn't understand it well enough before, either.  Just one little comment here.

2024-09-22 20:07 UTC, gonuke commented on cyclus/__init__.py
> +# import pymodule, eventhooks, pyinfile
Should we just delete this line?

2024-09-22 23:42 UTC, bennibbelink commented on cyclus/__init__.py
> +# import pymodule, eventhooks, pyinfile
Yes, thanks for catching that

2024-09-23 00:04 UTC, gonuke approved these changes
Thanks @bennibbelink

2024-09-23 00:04 UTC, merged